### ISSUE TITLE
Getting Following error for  Spill failed

### ISSUE THREAD

**Issue by atuldata** [cloudera/sqoop2#3]
there are null values in the table. these is the error I'm getting. 

2015-09-25 21:08:37,685 WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2015-09-25 21:08:38,294 INFO org.apache.hadoop.conf.Configuration.deprecation: session.id is deprecated. Instead, use dfs.metrics.session-id
2015-09-25 21:08:38,295 INFO org.apache.hadoop.metrics.jvm.JvmMetrics: Initializing JVM Metrics with processName=MAP, sessionId=
2015-09-25 21:08:38,914 INFO org.apache.hadoop.util.ProcessTree: setsid exited with exit code 0
2015-09-25 21:08:38,918 INFO org.apache.hadoop.mapred.Task:  Using ResourceCalculatorPlugin : org.apache.hadoop.util.LinuxResourceCalculatorPlugin@ca25138
2015-09-25 21:08:39,272 INFO org.apache.hadoop.mapred.MapTask: Processing split: org.apache.sqoop.job.mr.SqoopSplit@5f7e2943
2015-09-25 21:08:39,279 INFO org.apache.hadoop.mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
2015-09-25 21:08:39,283 INFO org.apache.hadoop.mapred.MapTask: io.sort.mb = 256
2015-09-25 21:08:39,447 INFO org.apache.hadoop.mapred.MapTask: data buffer = 204010960/255013696
2015-09-25 21:08:39,447 INFO org.apache.hadoop.mapred.MapTask: record buffer = 671088/838860
2015-09-25 21:08:39,568 INFO org.apache.sqoop.job.mr.SqoopMapper: Starting progress service
2015-09-25 21:08:39,570 INFO org.apache.sqoop.job.mr.SqoopMapper: Running extractor class org.apache.sqoop.connector.jdbc.GenericJdbcExtractor
2015-09-25 21:08:39,837 INFO org.apache.sqoop.connector.jdbc.GenericJdbcExtractor: Using query: SELECT advt_rollup_date,a_platform_id,p_platform_id,publisher_account_nk,site_nk,site_section_nk,page_nk,ad_unit_nk,rev_split,deal_type_uid,deal_cpm,rev_share_enabled,package_nk,deal_nk,advertiser_account_nk,order_nk,line_item_nk,ad_nk,line_item_pricing_model_code,line_item_pricing_rate,brand_nk,delivery_medium_code,screen_location_code,content_topic_group_sid,sales_channel_code,p_currency_code,a_currency_code,country_code,state_name,city_name,dma_code,ad_width,ad_height,ad_duration,ssp_elig,tot_requests,tot_discards,tot_impressions,tot_raw_billable_impressions,tot_billable_impressions,tot_clicks,tot_refresh_impressions,tot_billable_refresh_impressions,tot_view_conversions,tot_click_conversions,tot_raw_spend,tot_spend,tot_raw_conversion_spend,tot_conversion_spend,tot_mkt_elig_req,tot_mkt_requests,p_req_deliv_medium FROM mstr_datamart.temp_advt_supply_demand_geo_monthly_fact WHERE 14 <= rowId AND rowId <= 15
2015-09-25 21:09:31,496 INFO org.apache.hadoop.mapred.MapTask: Spilling map output: buffer full= true
2015-09-25 21:09:31,496 INFO org.apache.hadoop.mapred.MapTask: bufstart = 0; bufend = 204011138; bufvoid = 255013696
2015-09-25 21:09:31,496 INFO org.apache.hadoop.mapred.MapTask: kvstart = 0; kvend = 444368; length = 838860
2015-09-25 22:08:57,102 INFO org.apache.sqoop.job.mr.SqoopMapper: Stopping progress service
2015-09-25 22:08:57,115 INFO org.apache.hadoop.mapred.TaskLogsTruncater: Initializing logs' truncater with mapRetainSize=-1 and reduceRetainSize=-1
2015-09-25 22:08:57,118 WARN org.apache.hadoop.mapred.Child: Error running child
org.apache.sqoop.common.SqoopException: MAPRED_EXEC_0017:Error occurs during extractor run
    at org.apache.sqoop.job.mr.SqoopMapper.run(SqoopMapper.java:99)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:672)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:330)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: org.apache.sqoop.common.SqoopException: MAPRED_EXEC_0013:Cannot write to the data writer
    at org.apache.sqoop.job.mr.SqoopMapper$SqoopMapDataWriter.writeContent(SqoopMapper.java:153)
    at org.apache.sqoop.job.mr.SqoopMapper$SqoopMapDataWriter.writeArrayRecord(SqoopMapper.java:126)
    at org.apache.sqoop.connector.jdbc.GenericJdbcExtractor.extract(GenericJdbcExtractor.java:96)
    at org.apache.sqoop.connector.jdbc.GenericJdbcExtractor.extract(GenericJdbcExtractor.java:38)
    at org.apache.sqoop.job.mr.SqoopMapper.run(SqoopMapper.java:95)
    ... 7 more
Caused by: java.io.IOException: Spill failed
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:905)
    at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:601)
    at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:85)
    at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:106)
    at org.apache.sqoop.job.mr.SqoopMapper$SqoopMapDataWriter.writeContent(SqoopMapper.java:151)
    ... 11 more
Caused by: java.lang.NullPointerException
    at org.apache.sqoop.job.io.SqoopWritable.readFields(SqoopWritable.java:66)
    at org.apache.hadoop.io.WritableComparator.compare(WritableComparator.java:158)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.compare(MapTask.java:987)
    at org.apache.hadoop.util.QuickSort.sortInternal(QuickSort.java:99)
    at org.apache.hadoop.util.QuickSort.sort(QuickSort.java:63)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.sortAndSpill(MapTask.java:1277)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.access$1900(MapTask.java:724)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer$SpillThread.run(MapTask.java:1222)
2015-09-25 22:08:57,123 INFO org.apache.hadoop.mapred.Task: Runnning cleanup for the task

**Comment by atuldata** [comment]
Following is the job. 

{"job":{"driver-config-values":[{"id":8,"inputs":[{"id":24,"overrides":"","name":"throttlingConfig.numExtractors","value":"16","type":"INTEGER","editable":"ANY","sensitive":false},{"id":25,"overrides":"","name":"throttlingConfig.numLoaders","value":"16","type":"INTEGER","editable":"ANY","sensitive":false}],"name":"throttlingConfig","type":"JOB"}],"enabled":true,"from-connector-id":1,"update-user":null,"to-config-values":[{"id":17,"inputs":[{"id":38,"overrides":"","name":"toJobConfig.overrideNullValue","type":"BOOLEAN","editable":"ANY","sensitive":false},{"id":39,"overrides":"","name":"toJobConfig.nullValue","type":"STRING","editable":"ANY","size":255,"sensitive":false},{"id":40,"values":"TEXT_FILE,SEQUENCE_FILE","overrides":"","name":"toJobConfig.outputFormat","value":"SEQUENCE_FILE","type":"ENUM","editable":"ANY","sensitive":false},{"id":41,"values":"NONE,DEFAULT,DEFLATE,GZIP,BZIP2,LZO,LZ4,SNAPPY,CUSTOM","overrides":"","name":"toJobConfig.compression","value":"SNAPPY","type":"ENUM","editable":"ANY","sensitive":false},{"id":42,"overrides":"","name":"toJobConfig.customCompression","type":"STRING","editable":"ANY","size":255,"sensitive":false},{"id":43,"overrides":"","name":"toJobConfig.outputDirectory","value":"advt_supply_demand_geo_monthly_fact","type":"STRING","editable":"ANY","size":255,"sensitive":false}],"name":"toJobConfig","type":"JOB"}],"to-connector-id":2,"creation-date":1439573684178,"update-date":1443214849594,"creation-user":null,"id":25,"to-link-id":5,"from-config-values":[{"id":19,"inputs":[{"id":49,"overrides":"","name":"fromJobConfig.schemaName","value":"mstr_datamart","type":"STRING","editable":"ANY","size":50,"sensitive":false},{"id":50,"overrides":"","name":"fromJobConfig.tableName","value":"temp_advt_supply_demand_geo_monthly_fact","type":"STRING","editable":"ANY","size":50,"sensitive":false},{"id":51,"overrides":"","name":"fromJobConfig.sql","type":"STRING","editable":"ANY","size":2000,"sensitive":false},{"id":52,"overrides":"","name":"fromJobConfig.columns","value":"advt_rollup_date%2Ca_platform_id%2Cp_platform_id%2Cpublisher_account_nk%2Csite_nk%2Csite_section_nk%2Cpage_nk%2Cad_unit_nk%2Crev_split%2Cdeal_type_uid%2Cdeal_cpm%2Crev_share_enabled%2Cpackage_nk%2Cdeal_nk%2Cadvertiser_account_nk%2Corder_nk%2Cline_item_nk%2Cad_nk%2Cline_item_pricing_model_code%2Cline_item_pricing_rate%2Cbrand_nk%2Cdelivery_medium_code%2Cscreen_location_code%2Ccontent_topic_group_sid%2Csales_channel_code%2Cp_currency_code%2Ca_currency_code%2Ccountry_code%2Cstate_name%2Ccity_name%2Cdma_code%2Cad_width%2Cad_height%2Cad_duration%2Cssp_elig%2Ctot_requests%2Ctot_discards%2Ctot_impressions%2Ctot_raw_billable_impressions%2Ctot_billable_impressions%2Ctot_clicks%2Ctot_refresh_impressions%2Ctot_billable_refresh_impressions%2Ctot_view_conversions%2Ctot_click_conversions%2Ctot_raw_spend%2Ctot_spend%2Ctot_raw_conversion_spend%2Ctot_conversion_spend%2Ctot_mkt_elig_req%2Ctot_mkt_requests%2Cp_req_deliv_medium","type":"STRING","editable":"ANY","size":50,"sensitive":false},{"id":53,"overrides":"","name":"fromJobConfig.partitionColumn","value":"rowId","type":"STRING","editable":"ANY","size":50,"sensitive":false},{"id":54,"overrides":"","name":"fromJobConfig.allowNullValueInPartitionColumn","type":"BOOLEAN","editable":"ANY","sensitive":false},{"id":55,"overrides":"","name":"fromJobConfig.boundaryQuery","type":"STRING","editable":"ANY","size":50,"sensitive":false}],"name":"fromJobConfig","type":"JOB"}],"name":"advt_supply_demand_geo_monthly_fact","from-link-id":3}}

**Comment by jarcec** [comment]
Hi Atul,
could you report your troubles on [cdh-user](https://groups.google.com/a/cloudera.org/forum/#!forum/cdh-user) mailing list or on [our public JIRA](https://issues.cloudera.org/projects/DISTRO)?

Jarcec

**Comment by atuldata** [comment]
Sure
